# ✅ CONFIGURACIÓN RAILWAY OPTIMIZADA PARA HEALTH CHECK

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
numReplicas = 1
startCommand = "node backend/src/server.js"

# Variables de entorno de Railway
[variables]
NODE_ENV = "production"
PORT = "5000"
NEXT_TELEMETRY_DISABLED = "1"

# Para configurar en el Dashboard de Railway:
# JWT_SECRET = "tu_jwt_secret_super_seguro_aqui"  
# DATABASE_URL = "postgresql://usuario:password@host:puerto/database"