# ✅ CONFIGURACIÓN RAILWAY UNIFICADA (OPCIONAL)
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Variables de entorno (configurar en Railway Dashboard)
# NODE_ENV=production
# PORT=5000
# JWT_SECRET=tu_jwt_secret_super_seguro
# DATABASE_URL=postgresql://usuario:password@host:puerto/database

[variables]
NODE_ENV = "production"
PORT = "5000"